on: push
name: format and publish on tag
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: black
        uses: ./.github/actions/black

  pypi:
    runs-on: ubuntu-latest
    needs: ["black"]
    steps:
      - uses: actions/checkout@master
      - name: pypi
        uses: ./.github/actions/pypi
        if: startsWith(github.ref, 'refs/tags/')
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: ${{ secrets.TWINE_USERNAME }}
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
